### ISSUE TITLE
how to assign table to generator

### ISSUE THREAD

**Issue by MABIY** [smartnews/jpa-entity-generator#15]
l want to assign few table create jpa entity,not all .
how to set of entityGenConfig.yml .
can you help?

**Comment by seratch** [comment]
Unfortunately, at this moment, there is no way to limit the tables to generate entities. If you can express some matching rules to exclude them by regular expression, you can use `tableExclusionRules`. 
* https://github.com/smartnews/jpa-entity-generator/blob/v0.99.4/src/test/resources/entityGenConfig.yml#L28-L36

Actually, the implementation is quite simple. Personally, it would be reasonable to have new configuration like 1) `targetTableNameRules` + regexp, 2) `targetTableNames` (= a list of allowed tables), etc.. (pull requests are welcome)

* https://github.com/smartnews/jpa-entity-generator/blob/v0.99.4/src/main/java/com/smartnews/jpa_entity_generator/CodeGenerator.java#L56-L62

**Comment by seratch** [comment]
0.99.5 is out. Please try "tableScanMode + tableScanRules" out. https://github.com/smartnews/jpa-entity-generator/pull/19

**Comment by MABIY** [comment]
think you!

**Comment by seratch** [comment]
@MABIY My pleasure. If you like/use this library, please increment # of stars for it. 😄https://github.com/smartnews/jpa-entity-generator/stargazers

**Comment by MABIY** [comment]
> @MABIY My pleasure. If you like/use this library, please increment # of stars for it. https://github.com/smartnews/jpa-entity-generator/stargazers

ok,66 start become 67 start

**Comment by seratch** [comment]
Thank you 🙏
