### ISSUE TITLE
Table not exists if multiple DB schema exists

### ISSUE THREAD

**Issue by ironsweet** [smartnews/jpa-entity-generator#23]
I have multiple schemas. One has the table I need and one does not. Somehow I got "table not exists" error when importing from one schema. And yes, I have specified the right schema in connection string.

Assuming I want to generate entity for A.table1 but it complains B.table doesn't not exist.

I'm doing more test locally.

Updates:
Mysql 8.0.13 has this issue.
Mysql 5.1.46 is working.

**Comment by seratch** [comment]
Right, I have recognized that MySQL JDBC driver 6+ behaves differently. But I'm still not sure how we should deal with it yet.

**Comment by ironsweet** [comment]
Since it's a code gen tool, I'm totally fine if it's using a different version of mysql driver. Thanks~
