### ISSUE TITLE
Need a way to provide parameter to  entityGenConfig.yml

### ISSUE THREAD

**Issue by sanju-sfo** [smartnews/jpa-entity-generator#6]
It would be great to have ability to substitute jdbc url/password as parameter, so that it can be checked in to source control and build system can substitute these as parameter.

**Comment by seratch** [comment]
@sanju-sfo Thanks, fair enough. I've implemented the feature. We'll release the next version including the change. https://github.com/smartnews/jpa-entity-generator/pull/7

**Comment by seratch** [comment]
@sanju-sfo I just released version 0.99.3. Check it out when you have time.
