### ISSUE TITLE
tableExclusionRules not working

### ISSUE THREAD

**Issue by xadhatter** [smartnews/jpa-entity-generator#9]
I believe there is a bug with `tableExclusionRules`.  It does not appear to be working with the regular expressions I pass.

For example, say I have these tables:
```
a_table1
a_table2
b_table3
```
I want to exclude all tables that start with "a_" so I put the following in entityGenConfig.yml
```yaml
tableExclusionRules:
  - tableNames: ["a_.*"]
```
Yet these tables are still included.

My guess is the problem lies in `jpa-entity-generator/src/main/java/com/smartnews/jpa_entity_generator/CodeGenerator.java`

```java
boolean shouldExclude = originalConfig.getTableExclusionRules().stream().filter(rule -> rule.matches(tableName)).count() > 0;
```
should be
```java
boolean shouldExclude = originalConfig.getTableExclusionRules().stream().filter(rule -> tableName.matches(rule)).count() > 0;
```
Notice the `tableName` and `rule` switch on the `matches` call.

Please let me know if I am doing something wrong.  Your project looks great and I'm excited to use it!

Also, it'd be great if there was an `tableInclusionRules` as well :D

**Comment by seratch** [comment]
Thank you. You're right. That is a bug. I will fix it.

**Comment by seratch** [comment]
Regarding `tableInclusionRules`, it may be useful for a portion of users.

When a user specifies `tableInclusionRules` in the configuration file, the possible behavior will be either of:

* (A) All the rules defined in `tableExclusionRules` will be just ignored at all
* (B) If a table matches both `tableInclusionRules` and `tableExclusionRules`, the table must be excluded.

I prefer (B) over (A). If we have the feature in the future, I would like to go with the specification supporting the behavior (B). 

I won't work on it. If you really need the feature very soon, could you make a pull request to add the feature?
